/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LineaBlancaRouteImport } from './routes/linea-blanca'
import { Route as GarantiasRouteImport } from './routes/garantias'
import { Route as FinanciamientoRouteImport } from './routes/financiamiento'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as BordadosRouteImport } from './routes/bordados'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated.admin.seo'
import { Route as AuthenticatedAdminReportesRouteImport } from './routes/_authenticated.admin.reportes'
import { Route as AuthenticatedAdminPromocionesRouteImport } from './routes/_authenticated.admin.promociones'
import { Route as AuthenticatedAdminProductosRouteImport } from './routes/_authenticated.admin.productos'
import { Route as AuthenticatedAdminPreviewRouteImport } from './routes/_authenticated.admin.preview'
import { Route as AuthenticatedAdminContenidoRouteImport } from './routes/_authenticated.admin.contenido'
import { Route as AuthenticatedAdminContactoRouteImport } from './routes/_authenticated.admin.contacto'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated.admin.categorias'
import { Route as AuthenticatedAdminCambiosRouteImport } from './routes/_authenticated.admin.cambios'
import { Route as AuthenticatedAdminBrandingRouteImport } from './routes/_authenticated.admin.branding'
import { Route as AuthenticatedAdminBordadosRouteImport } from './routes/_authenticated.admin.bordados'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated.admin.auditoria'

const LineaBlancaRoute = LineaBlancaRouteImport.update({
  id: '/linea-blanca',
  path: '/linea-blanca',
  getParentRoute: () => rootRouteImport,
} as any)
const GarantiasRoute = GarantiasRouteImport.update({
  id: '/garantias',
  path: '/garantias',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanciamientoRoute = FinanciamientoRouteImport.update({
  id: '/financiamiento',
  path: '/financiamiento',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const BordadosRoute = BordadosRouteImport.update({
  id: '/bordados',
  path: '/bordados',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReportesRoute =
  AuthenticatedAdminReportesRouteImport.update({
    id: '/reportes',
    path: '/reportes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPromocionesRoute =
  AuthenticatedAdminPromocionesRouteImport.update({
    id: '/promociones',
    path: '/promociones',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductosRoute =
  AuthenticatedAdminProductosRouteImport.update({
    id: '/productos',
    path: '/productos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPreviewRoute =
  AuthenticatedAdminPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContenidoRoute =
  AuthenticatedAdminContenidoRouteImport.update({
    id: '/contenido',
    path: '/contenido',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContactoRoute =
  AuthenticatedAdminContactoRouteImport.update({
    id: '/contacto',
    path: '/contacto',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCambiosRoute =
  AuthenticatedAdminCambiosRouteImport.update({
    id: '/cambios',
    path: '/cambios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBrandingRoute =
  AuthenticatedAdminBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBordadosRoute =
  AuthenticatedAdminBordadosRouteImport.update({
    id: '/bordados',
    path: '/bordados',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bordados': typeof BordadosRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/financiamiento': typeof FinanciamientoRoute
  '/garantias': typeof GarantiasRoute
  '/linea-blanca': typeof LineaBlancaRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/bordados': typeof AuthenticatedAdminBordadosRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/cambios': typeof AuthenticatedAdminCambiosRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/contacto': typeof AuthenticatedAdminContactoRoute
  '/admin/contenido': typeof AuthenticatedAdminContenidoRoute
  '/admin/preview': typeof AuthenticatedAdminPreviewRoute
  '/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/admin/promociones': typeof AuthenticatedAdminPromocionesRoute
  '/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bordados': typeof BordadosRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/financiamiento': typeof FinanciamientoRoute
  '/garantias': typeof GarantiasRoute
  '/linea-blanca': typeof LineaBlancaRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/bordados': typeof AuthenticatedAdminBordadosRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/cambios': typeof AuthenticatedAdminCambiosRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/contacto': typeof AuthenticatedAdminContactoRoute
  '/admin/contenido': typeof AuthenticatedAdminContenidoRoute
  '/admin/preview': typeof AuthenticatedAdminPreviewRoute
  '/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/admin/promociones': typeof AuthenticatedAdminPromocionesRoute
  '/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/bordados': typeof BordadosRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/financiamiento': typeof FinanciamientoRoute
  '/garantias': typeof GarantiasRoute
  '/linea-blanca': typeof LineaBlancaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/bordados': typeof AuthenticatedAdminBordadosRoute
  '/_authenticated/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/_authenticated/admin/cambios': typeof AuthenticatedAdminCambiosRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/contacto': typeof AuthenticatedAdminContactoRoute
  '/_authenticated/admin/contenido': typeof AuthenticatedAdminContenidoRoute
  '/_authenticated/admin/preview': typeof AuthenticatedAdminPreviewRoute
  '/_authenticated/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/_authenticated/admin/promociones': typeof AuthenticatedAdminPromocionesRoute
  '/_authenticated/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bordados'
    | '/catalogo'
    | '/contacto'
    | '/financiamiento'
    | '/garantias'
    | '/linea-blanca'
    | '/admin'
    | '/admin/auditoria'
    | '/admin/bordados'
    | '/admin/branding'
    | '/admin/cambios'
    | '/admin/categorias'
    | '/admin/contacto'
    | '/admin/contenido'
    | '/admin/preview'
    | '/admin/productos'
    | '/admin/promociones'
    | '/admin/reportes'
    | '/admin/seo'
    | '/api/public/bootstrap-admin'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bordados'
    | '/catalogo'
    | '/contacto'
    | '/financiamiento'
    | '/garantias'
    | '/linea-blanca'
    | '/admin/auditoria'
    | '/admin/bordados'
    | '/admin/branding'
    | '/admin/cambios'
    | '/admin/categorias'
    | '/admin/contacto'
    | '/admin/contenido'
    | '/admin/preview'
    | '/admin/productos'
    | '/admin/promociones'
    | '/admin/reportes'
    | '/admin/seo'
    | '/api/public/bootstrap-admin'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bordados'
    | '/catalogo'
    | '/contacto'
    | '/financiamiento'
    | '/garantias'
    | '/linea-blanca'
    | '/_authenticated/admin'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/bordados'
    | '/_authenticated/admin/branding'
    | '/_authenticated/admin/cambios'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/contacto'
    | '/_authenticated/admin/contenido'
    | '/_authenticated/admin/preview'
    | '/_authenticated/admin/productos'
    | '/_authenticated/admin/promociones'
    | '/_authenticated/admin/reportes'
    | '/_authenticated/admin/seo'
    | '/api/public/bootstrap-admin'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  BordadosRoute: typeof BordadosRoute
  CatalogoRoute: typeof CatalogoRoute
  ContactoRoute: typeof ContactoRoute
  FinanciamientoRoute: typeof FinanciamientoRoute
  GarantiasRoute: typeof GarantiasRoute
  LineaBlancaRoute: typeof LineaBlancaRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/linea-blanca': {
      id: '/linea-blanca'
      path: '/linea-blanca'
      fullPath: '/linea-blanca'
      preLoaderRoute: typeof LineaBlancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garantias': {
      id: '/garantias'
      path: '/garantias'
      fullPath: '/garantias'
      preLoaderRoute: typeof GarantiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financiamiento': {
      id: '/financiamiento'
      path: '/financiamiento'
      fullPath: '/financiamiento'
      preLoaderRoute: typeof FinanciamientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bordados': {
      id: '/bordados'
      path: '/bordados'
      fullPath: '/bordados'
      preLoaderRoute: typeof BordadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reportes': {
      id: '/_authenticated/admin/reportes'
      path: '/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AuthenticatedAdminReportesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/promociones': {
      id: '/_authenticated/admin/promociones'
      path: '/promociones'
      fullPath: '/admin/promociones'
      preLoaderRoute: typeof AuthenticatedAdminPromocionesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/productos': {
      id: '/_authenticated/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AuthenticatedAdminProductosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/preview': {
      id: '/_authenticated/admin/preview'
      path: '/preview'
      fullPath: '/admin/preview'
      preLoaderRoute: typeof AuthenticatedAdminPreviewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contenido': {
      id: '/_authenticated/admin/contenido'
      path: '/contenido'
      fullPath: '/admin/contenido'
      preLoaderRoute: typeof AuthenticatedAdminContenidoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contacto': {
      id: '/_authenticated/admin/contacto'
      path: '/contacto'
      fullPath: '/admin/contacto'
      preLoaderRoute: typeof AuthenticatedAdminContactoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cambios': {
      id: '/_authenticated/admin/cambios'
      path: '/cambios'
      fullPath: '/admin/cambios'
      preLoaderRoute: typeof AuthenticatedAdminCambiosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/branding': {
      id: '/_authenticated/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AuthenticatedAdminBrandingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bordados': {
      id: '/_authenticated/admin/bordados'
      path: '/bordados'
      fullPath: '/admin/bordados'
      preLoaderRoute: typeof AuthenticatedAdminBordadosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminBordadosRoute: typeof AuthenticatedAdminBordadosRoute
  AuthenticatedAdminBrandingRoute: typeof AuthenticatedAdminBrandingRoute
  AuthenticatedAdminCambiosRoute: typeof AuthenticatedAdminCambiosRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminContactoRoute: typeof AuthenticatedAdminContactoRoute
  AuthenticatedAdminContenidoRoute: typeof AuthenticatedAdminContenidoRoute
  AuthenticatedAdminPreviewRoute: typeof AuthenticatedAdminPreviewRoute
  AuthenticatedAdminProductosRoute: typeof AuthenticatedAdminProductosRoute
  AuthenticatedAdminPromocionesRoute: typeof AuthenticatedAdminPromocionesRoute
  AuthenticatedAdminReportesRoute: typeof AuthenticatedAdminReportesRoute
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminBordadosRoute: AuthenticatedAdminBordadosRoute,
  AuthenticatedAdminBrandingRoute: AuthenticatedAdminBrandingRoute,
  AuthenticatedAdminCambiosRoute: AuthenticatedAdminCambiosRoute,
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminContactoRoute: AuthenticatedAdminContactoRoute,
  AuthenticatedAdminContenidoRoute: AuthenticatedAdminContenidoRoute,
  AuthenticatedAdminPreviewRoute: AuthenticatedAdminPreviewRoute,
  AuthenticatedAdminProductosRoute: AuthenticatedAdminProductosRoute,
  AuthenticatedAdminPromocionesRoute: AuthenticatedAdminPromocionesRoute,
  AuthenticatedAdminReportesRoute: AuthenticatedAdminReportesRoute,
  AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  BordadosRoute: BordadosRoute,
  CatalogoRoute: CatalogoRoute,
  ContactoRoute: ContactoRoute,
  FinanciamientoRoute: FinanciamientoRoute,
  GarantiasRoute: GarantiasRoute,
  LineaBlancaRoute: LineaBlancaRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
