/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LineaBlancaRouteImport } from './routes/linea-blanca'
import { Route as GarantiasRouteImport } from './routes/garantias'
import { Route as FinanciamientoRouteImport } from './routes/financiamiento'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as BordadosRouteImport } from './routes/bordados'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedAdminProductosRouteImport } from './routes/_authenticated.admin.productos'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated.admin.categorias'
import { Route as AuthenticatedAdminBordadosRouteImport } from './routes/_authenticated.admin.bordados'

const LineaBlancaRoute = LineaBlancaRouteImport.update({
  id: '/linea-blanca',
  path: '/linea-blanca',
  getParentRoute: () => rootRouteImport,
} as any)
const GarantiasRoute = GarantiasRouteImport.update({
  id: '/garantias',
  path: '/garantias',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanciamientoRoute = FinanciamientoRouteImport.update({
  id: '/financiamiento',
  path: '/financiamiento',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const BordadosRoute = BordadosRouteImport.update({
  id: '/bordados',
  path: '/bordados',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProductosRoute =
  AuthenticatedAdminProductosRouteImport.update({
    id: '/productos',
    path: '/productos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBordadosRoute =
  AuthenticatedAdminBordadosRouteImport.update({
    id: '/bordados',
    path: '/bordados',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bordados': typeof BordadosRoute
  '/contacto': typeof ContactoRoute
  '/financiamiento': typeof FinanciamientoRoute
  '/garantias': typeof GarantiasRoute
  '/linea-blanca': typeof LineaBlancaRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/bordados': typeof AuthenticatedAdminBordadosRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bordados': typeof BordadosRoute
  '/contacto': typeof ContactoRoute
  '/financiamiento': typeof FinanciamientoRoute
  '/garantias': typeof GarantiasRoute
  '/linea-blanca': typeof LineaBlancaRoute
  '/admin/bordados': typeof AuthenticatedAdminBordadosRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/bordados': typeof BordadosRoute
  '/contacto': typeof ContactoRoute
  '/financiamiento': typeof FinanciamientoRoute
  '/garantias': typeof GarantiasRoute
  '/linea-blanca': typeof LineaBlancaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/bordados': typeof AuthenticatedAdminBordadosRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bordados'
    | '/contacto'
    | '/financiamiento'
    | '/garantias'
    | '/linea-blanca'
    | '/admin'
    | '/admin/bordados'
    | '/admin/categorias'
    | '/admin/productos'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bordados'
    | '/contacto'
    | '/financiamiento'
    | '/garantias'
    | '/linea-blanca'
    | '/admin/bordados'
    | '/admin/categorias'
    | '/admin/productos'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bordados'
    | '/contacto'
    | '/financiamiento'
    | '/garantias'
    | '/linea-blanca'
    | '/_authenticated/admin'
    | '/_authenticated/admin/bordados'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/productos'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  BordadosRoute: typeof BordadosRoute
  ContactoRoute: typeof ContactoRoute
  FinanciamientoRoute: typeof FinanciamientoRoute
  GarantiasRoute: typeof GarantiasRoute
  LineaBlancaRoute: typeof LineaBlancaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/linea-blanca': {
      id: '/linea-blanca'
      path: '/linea-blanca'
      fullPath: '/linea-blanca'
      preLoaderRoute: typeof LineaBlancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garantias': {
      id: '/garantias'
      path: '/garantias'
      fullPath: '/garantias'
      preLoaderRoute: typeof GarantiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financiamiento': {
      id: '/financiamiento'
      path: '/financiamiento'
      fullPath: '/financiamiento'
      preLoaderRoute: typeof FinanciamientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bordados': {
      id: '/bordados'
      path: '/bordados'
      fullPath: '/bordados'
      preLoaderRoute: typeof BordadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/productos': {
      id: '/_authenticated/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AuthenticatedAdminProductosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bordados': {
      id: '/_authenticated/admin/bordados'
      path: '/bordados'
      fullPath: '/admin/bordados'
      preLoaderRoute: typeof AuthenticatedAdminBordadosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBordadosRoute: typeof AuthenticatedAdminBordadosRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminProductosRoute: typeof AuthenticatedAdminProductosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBordadosRoute: AuthenticatedAdminBordadosRoute,
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminProductosRoute: AuthenticatedAdminProductosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  BordadosRoute: BordadosRoute,
  ContactoRoute: ContactoRoute,
  FinanciamientoRoute: FinanciamientoRoute,
  GarantiasRoute: GarantiasRoute,
  LineaBlancaRoute: LineaBlancaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
