/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BordadosRouteImport } from './routes/bordados'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as FinanciamientoRouteImport } from './routes/financiamiento'
import { Route as GarantiasRouteImport } from './routes/garantias'
import { Route as LineaBlancaRouteImport } from './routes/linea-blanca'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ModuloGarantiasRouteImport } from './routes/modulo-garantias'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as PedidoNumeroRouteImport } from './routes/pedido.$numero'
import { Route as ReporteGarantiaIdRouteImport } from './routes/reporte-garantia.$id'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated.admin.auditoria'
import { Route as AuthenticatedAdminBitacoraRouteImport } from './routes/_authenticated.admin.bitacora'
import { Route as AuthenticatedAdminBordadosRouteImport } from './routes/_authenticated.admin.bordados'
import { Route as AuthenticatedAdminBordadosServiciosRouteImport } from './routes/_authenticated.admin.bordados-servicios'
import { Route as AuthenticatedAdminBrandingRouteImport } from './routes/_authenticated.admin.branding'
import { Route as AuthenticatedAdminCalendarioRouteImport } from './routes/_authenticated.admin.calendario'
import { Route as AuthenticatedAdminCambiosRouteImport } from './routes/_authenticated.admin.cambios'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated.admin.categorias'
import { Route as AuthenticatedAdminColaboradoresRouteImport } from './routes/_authenticated.admin.colaboradores'
import { Route as AuthenticatedAdminContactoRouteImport } from './routes/_authenticated.admin.contacto'
import { Route as AuthenticatedAdminContenidoRouteImport } from './routes/_authenticated.admin.contenido'
import { Route as AuthenticatedAdminPreviewRouteImport } from './routes/_authenticated.admin.preview'
import { Route as AuthenticatedAdminProductosRouteImport } from './routes/_authenticated.admin.productos'
import { Route as AuthenticatedAdminPromocionesRouteImport } from './routes/_authenticated.admin.promociones'
import { Route as AuthenticatedAdminReportesRouteImport } from './routes/_authenticated.admin.reportes'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated.admin.seo'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated.admin.usuarios'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as ApiPublicHooksRefreshHomeGalleryRouteImport } from './routes/api/public/hooks/refresh-home-gallery'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BordadosRoute = BordadosRouteImport.update({
  id: '/bordados',
  path: '/bordados',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanciamientoRoute = FinanciamientoRouteImport.update({
  id: '/financiamiento',
  path: '/financiamiento',
  getParentRoute: () => rootRouteImport,
} as any)
const GarantiasRoute = GarantiasRouteImport.update({
  id: '/garantias',
  path: '/garantias',
  getParentRoute: () => rootRouteImport,
} as any)
const LineaBlancaRoute = LineaBlancaRouteImport.update({
  id: '/linea-blanca',
  path: '/linea-blanca',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuloGarantiasRoute = ModuloGarantiasRouteImport.update({
  id: '/modulo-garantias',
  path: '/modulo-garantias',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PedidoNumeroRoute = PedidoNumeroRouteImport.update({
  id: '/pedido/$numero',
  path: '/pedido/$numero',
  getParentRoute: () => rootRouteImport,
} as any)
const ReporteGarantiaIdRoute = ReporteGarantiaIdRouteImport.update({
  id: '/reporte-garantia/$id',
  path: '/reporte-garantia/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBitacoraRoute =
  AuthenticatedAdminBitacoraRouteImport.update({
    id: '/bitacora',
    path: '/bitacora',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBordadosRoute =
  AuthenticatedAdminBordadosRouteImport.update({
    id: '/bordados',
    path: '/bordados',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBordadosServiciosRoute =
  AuthenticatedAdminBordadosServiciosRouteImport.update({
    id: '/bordados-servicios',
    path: '/bordados-servicios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBrandingRoute =
  AuthenticatedAdminBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCalendarioRoute =
  AuthenticatedAdminCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCambiosRoute =
  AuthenticatedAdminCambiosRouteImport.update({
    id: '/cambios',
    path: '/cambios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminColaboradoresRoute =
  AuthenticatedAdminColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContactoRoute =
  AuthenticatedAdminContactoRouteImport.update({
    id: '/contacto',
    path: '/contacto',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContenidoRoute =
  AuthenticatedAdminContenidoRouteImport.update({
    id: '/contenido',
    path: '/contenido',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPreviewRoute =
  AuthenticatedAdminPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductosRoute =
  AuthenticatedAdminProductosRouteImport.update({
    id: '/productos',
    path: '/productos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPromocionesRoute =
  AuthenticatedAdminPromocionesRouteImport.update({
    id: '/promociones',
    path: '/promociones',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportesRoute =
  AuthenticatedAdminReportesRouteImport.update({
    id: '/reportes',
    path: '/reportes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshHomeGalleryRoute =
  ApiPublicHooksRefreshHomeGalleryRouteImport.update({
    id: '/api/public/hooks/refresh-home-gallery',
    path: '/api/public/hooks/refresh-home-gallery',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bordados': typeof BordadosRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/financiamiento': typeof FinanciamientoRoute
  '/garantias': typeof GarantiasRoute
  '/linea-blanca': typeof LineaBlancaRoute
  '/mcp': typeof McpRoute
  '/modulo-garantias': typeof ModuloGarantiasRoute
  '/portal': typeof PortalRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/pedido/$numero': typeof PedidoNumeroRoute
  '/reporte-garantia/$id': typeof ReporteGarantiaIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/bitacora': typeof AuthenticatedAdminBitacoraRoute
  '/admin/bordados': typeof AuthenticatedAdminBordadosRoute
  '/admin/bordados-servicios': typeof AuthenticatedAdminBordadosServiciosRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/admin/cambios': typeof AuthenticatedAdminCambiosRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/colaboradores': typeof AuthenticatedAdminColaboradoresRoute
  '/admin/contacto': typeof AuthenticatedAdminContactoRoute
  '/admin/contenido': typeof AuthenticatedAdminContenidoRoute
  '/admin/preview': typeof AuthenticatedAdminPreviewRoute
  '/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/admin/promociones': typeof AuthenticatedAdminPromocionesRoute
  '/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/refresh-home-gallery': typeof ApiPublicHooksRefreshHomeGalleryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bordados': typeof BordadosRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/financiamiento': typeof FinanciamientoRoute
  '/garantias': typeof GarantiasRoute
  '/linea-blanca': typeof LineaBlancaRoute
  '/mcp': typeof McpRoute
  '/modulo-garantias': typeof ModuloGarantiasRoute
  '/portal': typeof PortalRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/pedido/$numero': typeof PedidoNumeroRoute
  '/reporte-garantia/$id': typeof ReporteGarantiaIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/bitacora': typeof AuthenticatedAdminBitacoraRoute
  '/admin/bordados': typeof AuthenticatedAdminBordadosRoute
  '/admin/bordados-servicios': typeof AuthenticatedAdminBordadosServiciosRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/admin/cambios': typeof AuthenticatedAdminCambiosRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/colaboradores': typeof AuthenticatedAdminColaboradoresRoute
  '/admin/contacto': typeof AuthenticatedAdminContactoRoute
  '/admin/contenido': typeof AuthenticatedAdminContenidoRoute
  '/admin/preview': typeof AuthenticatedAdminPreviewRoute
  '/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/admin/promociones': typeof AuthenticatedAdminPromocionesRoute
  '/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/refresh-home-gallery': typeof ApiPublicHooksRefreshHomeGalleryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/bordados': typeof BordadosRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/financiamiento': typeof FinanciamientoRoute
  '/garantias': typeof GarantiasRoute
  '/linea-blanca': typeof LineaBlancaRoute
  '/mcp': typeof McpRoute
  '/modulo-garantias': typeof ModuloGarantiasRoute
  '/portal': typeof PortalRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/pedido/$numero': typeof PedidoNumeroRoute
  '/reporte-garantia/$id': typeof ReporteGarantiaIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/bitacora': typeof AuthenticatedAdminBitacoraRoute
  '/_authenticated/admin/bordados': typeof AuthenticatedAdminBordadosRoute
  '/_authenticated/admin/bordados-servicios': typeof AuthenticatedAdminBordadosServiciosRoute
  '/_authenticated/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/_authenticated/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/_authenticated/admin/cambios': typeof AuthenticatedAdminCambiosRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/colaboradores': typeof AuthenticatedAdminColaboradoresRoute
  '/_authenticated/admin/contacto': typeof AuthenticatedAdminContactoRoute
  '/_authenticated/admin/contenido': typeof AuthenticatedAdminContenidoRoute
  '/_authenticated/admin/preview': typeof AuthenticatedAdminPreviewRoute
  '/_authenticated/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/_authenticated/admin/promociones': typeof AuthenticatedAdminPromocionesRoute
  '/_authenticated/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/refresh-home-gallery': typeof ApiPublicHooksRefreshHomeGalleryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bordados'
    | '/catalogo'
    | '/contacto'
    | '/financiamiento'
    | '/garantias'
    | '/linea-blanca'
    | '/mcp'
    | '/modulo-garantias'
    | '/portal'
    | '/privacidad'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/pedido/$numero'
    | '/reporte-garantia/$id'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/auditoria'
    | '/admin/bitacora'
    | '/admin/bordados'
    | '/admin/bordados-servicios'
    | '/admin/branding'
    | '/admin/calendario'
    | '/admin/cambios'
    | '/admin/categorias'
    | '/admin/colaboradores'
    | '/admin/contacto'
    | '/admin/contenido'
    | '/admin/preview'
    | '/admin/productos'
    | '/admin/promociones'
    | '/admin/reportes'
    | '/admin/seo'
    | '/admin/usuarios'
    | '/api/public/bootstrap-admin'
    | '/admin/'
    | '/api/public/hooks/refresh-home-gallery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bordados'
    | '/catalogo'
    | '/contacto'
    | '/financiamiento'
    | '/garantias'
    | '/linea-blanca'
    | '/mcp'
    | '/modulo-garantias'
    | '/portal'
    | '/privacidad'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/pedido/$numero'
    | '/reporte-garantia/$id'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/auditoria'
    | '/admin/bitacora'
    | '/admin/bordados'
    | '/admin/bordados-servicios'
    | '/admin/branding'
    | '/admin/calendario'
    | '/admin/cambios'
    | '/admin/categorias'
    | '/admin/colaboradores'
    | '/admin/contacto'
    | '/admin/contenido'
    | '/admin/preview'
    | '/admin/productos'
    | '/admin/promociones'
    | '/admin/reportes'
    | '/admin/seo'
    | '/admin/usuarios'
    | '/api/public/bootstrap-admin'
    | '/admin'
    | '/api/public/hooks/refresh-home-gallery'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bordados'
    | '/catalogo'
    | '/contacto'
    | '/financiamiento'
    | '/garantias'
    | '/linea-blanca'
    | '/mcp'
    | '/modulo-garantias'
    | '/portal'
    | '/privacidad'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/pedido/$numero'
    | '/reporte-garantia/$id'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/bitacora'
    | '/_authenticated/admin/bordados'
    | '/_authenticated/admin/bordados-servicios'
    | '/_authenticated/admin/branding'
    | '/_authenticated/admin/calendario'
    | '/_authenticated/admin/cambios'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/colaboradores'
    | '/_authenticated/admin/contacto'
    | '/_authenticated/admin/contenido'
    | '/_authenticated/admin/preview'
    | '/_authenticated/admin/productos'
    | '/_authenticated/admin/promociones'
    | '/_authenticated/admin/reportes'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/usuarios'
    | '/api/public/bootstrap-admin'
    | '/_authenticated/admin/'
    | '/api/public/hooks/refresh-home-gallery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  BordadosRoute: typeof BordadosRoute
  CatalogoRoute: typeof CatalogoRoute
  ContactoRoute: typeof ContactoRoute
  FinanciamientoRoute: typeof FinanciamientoRoute
  GarantiasRoute: typeof GarantiasRoute
  LineaBlancaRoute: typeof LineaBlancaRoute
  McpRoute: typeof McpRoute
  ModuloGarantiasRoute: typeof ModuloGarantiasRoute
  PortalRoute: typeof PortalRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  PedidoNumeroRoute: typeof PedidoNumeroRoute
  ReporteGarantiaIdRoute: typeof ReporteGarantiaIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
  ApiPublicHooksRefreshHomeGalleryRoute: typeof ApiPublicHooksRefreshHomeGalleryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bordados': {
      id: '/bordados'
      path: '/bordados'
      fullPath: '/bordados'
      preLoaderRoute: typeof BordadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financiamiento': {
      id: '/financiamiento'
      path: '/financiamiento'
      fullPath: '/financiamiento'
      preLoaderRoute: typeof FinanciamientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garantias': {
      id: '/garantias'
      path: '/garantias'
      fullPath: '/garantias'
      preLoaderRoute: typeof GarantiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linea-blanca': {
      id: '/linea-blanca'
      path: '/linea-blanca'
      fullPath: '/linea-blanca'
      preLoaderRoute: typeof LineaBlancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulo-garantias': {
      id: '/modulo-garantias'
      path: '/modulo-garantias'
      fullPath: '/modulo-garantias'
      preLoaderRoute: typeof ModuloGarantiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/pedido/$numero': {
      id: '/pedido/$numero'
      path: '/pedido/$numero'
      fullPath: '/pedido/$numero'
      preLoaderRoute: typeof PedidoNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporte-garantia/$id': {
      id: '/reporte-garantia/$id'
      path: '/reporte-garantia/$id'
      fullPath: '/reporte-garantia/$id'
      preLoaderRoute: typeof ReporteGarantiaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bitacora': {
      id: '/_authenticated/admin/bitacora'
      path: '/bitacora'
      fullPath: '/admin/bitacora'
      preLoaderRoute: typeof AuthenticatedAdminBitacoraRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bordados': {
      id: '/_authenticated/admin/bordados'
      path: '/bordados'
      fullPath: '/admin/bordados'
      preLoaderRoute: typeof AuthenticatedAdminBordadosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bordados-servicios': {
      id: '/_authenticated/admin/bordados-servicios'
      path: '/bordados-servicios'
      fullPath: '/admin/bordados-servicios'
      preLoaderRoute: typeof AuthenticatedAdminBordadosServiciosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/branding': {
      id: '/_authenticated/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AuthenticatedAdminBrandingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/calendario': {
      id: '/_authenticated/admin/calendario'
      path: '/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AuthenticatedAdminCalendarioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cambios': {
      id: '/_authenticated/admin/cambios'
      path: '/cambios'
      fullPath: '/admin/cambios'
      preLoaderRoute: typeof AuthenticatedAdminCambiosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/colaboradores': {
      id: '/_authenticated/admin/colaboradores'
      path: '/colaboradores'
      fullPath: '/admin/colaboradores'
      preLoaderRoute: typeof AuthenticatedAdminColaboradoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contacto': {
      id: '/_authenticated/admin/contacto'
      path: '/contacto'
      fullPath: '/admin/contacto'
      preLoaderRoute: typeof AuthenticatedAdminContactoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contenido': {
      id: '/_authenticated/admin/contenido'
      path: '/contenido'
      fullPath: '/admin/contenido'
      preLoaderRoute: typeof AuthenticatedAdminContenidoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/preview': {
      id: '/_authenticated/admin/preview'
      path: '/preview'
      fullPath: '/admin/preview'
      preLoaderRoute: typeof AuthenticatedAdminPreviewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/productos': {
      id: '/_authenticated/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AuthenticatedAdminProductosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/promociones': {
      id: '/_authenticated/admin/promociones'
      path: '/promociones'
      fullPath: '/admin/promociones'
      preLoaderRoute: typeof AuthenticatedAdminPromocionesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reportes': {
      id: '/_authenticated/admin/reportes'
      path: '/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AuthenticatedAdminReportesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-home-gallery': {
      id: '/api/public/hooks/refresh-home-gallery'
      path: '/api/public/hooks/refresh-home-gallery'
      fullPath: '/api/public/hooks/refresh-home-gallery'
      preLoaderRoute: typeof ApiPublicHooksRefreshHomeGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminBitacoraRoute: typeof AuthenticatedAdminBitacoraRoute
  AuthenticatedAdminBordadosRoute: typeof AuthenticatedAdminBordadosRoute
  AuthenticatedAdminBordadosServiciosRoute: typeof AuthenticatedAdminBordadosServiciosRoute
  AuthenticatedAdminBrandingRoute: typeof AuthenticatedAdminBrandingRoute
  AuthenticatedAdminCalendarioRoute: typeof AuthenticatedAdminCalendarioRoute
  AuthenticatedAdminCambiosRoute: typeof AuthenticatedAdminCambiosRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminColaboradoresRoute: typeof AuthenticatedAdminColaboradoresRoute
  AuthenticatedAdminContactoRoute: typeof AuthenticatedAdminContactoRoute
  AuthenticatedAdminContenidoRoute: typeof AuthenticatedAdminContenidoRoute
  AuthenticatedAdminPreviewRoute: typeof AuthenticatedAdminPreviewRoute
  AuthenticatedAdminProductosRoute: typeof AuthenticatedAdminProductosRoute
  AuthenticatedAdminPromocionesRoute: typeof AuthenticatedAdminPromocionesRoute
  AuthenticatedAdminReportesRoute: typeof AuthenticatedAdminReportesRoute
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminBitacoraRoute: AuthenticatedAdminBitacoraRoute,
  AuthenticatedAdminBordadosRoute: AuthenticatedAdminBordadosRoute,
  AuthenticatedAdminBordadosServiciosRoute:
    AuthenticatedAdminBordadosServiciosRoute,
  AuthenticatedAdminBrandingRoute: AuthenticatedAdminBrandingRoute,
  AuthenticatedAdminCalendarioRoute: AuthenticatedAdminCalendarioRoute,
  AuthenticatedAdminCambiosRoute: AuthenticatedAdminCambiosRoute,
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminColaboradoresRoute: AuthenticatedAdminColaboradoresRoute,
  AuthenticatedAdminContactoRoute: AuthenticatedAdminContactoRoute,
  AuthenticatedAdminContenidoRoute: AuthenticatedAdminContenidoRoute,
  AuthenticatedAdminPreviewRoute: AuthenticatedAdminPreviewRoute,
  AuthenticatedAdminProductosRoute: AuthenticatedAdminProductosRoute,
  AuthenticatedAdminPromocionesRoute: AuthenticatedAdminPromocionesRoute,
  AuthenticatedAdminReportesRoute: AuthenticatedAdminReportesRoute,
  AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  BordadosRoute: BordadosRoute,
  CatalogoRoute: CatalogoRoute,
  ContactoRoute: ContactoRoute,
  FinanciamientoRoute: FinanciamientoRoute,
  GarantiasRoute: GarantiasRoute,
  LineaBlancaRoute: LineaBlancaRoute,
  McpRoute: McpRoute,
  ModuloGarantiasRoute: ModuloGarantiasRoute,
  PortalRoute: PortalRoute,
  PrivacidadRoute: PrivacidadRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  PedidoNumeroRoute: PedidoNumeroRoute,
  ReporteGarantiaIdRoute: ReporteGarantiaIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
  ApiPublicHooksRefreshHomeGalleryRoute: ApiPublicHooksRefreshHomeGalleryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
